vaadin:
  launch-browser: false

logging:
  level:
    org.atmosphere: warn

spring:
  mustache:
    check-template-location: false
  application:
    name: linkedin-bot
  liquibase:
    change-log: 'classpath:db-migrations/changelog.xml'
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  datasource:
    url: "jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?currentSchema=${DATABASE_SCHEMA}"
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    platform: POSTGRESQL
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
      show_sql: true
    properties.hibernate.temp.use_jdbc_metadata_defaults: false

server:
  port: ${PORT:5000}

telegram:
  bot:
    name: ${BOT_NAME}
    token: ${BOT_TOKEN}

admin:
  first:
    user: ${ADMIN_FIRST_USER}
    login: ${ADMIN_FIRST_LOGIN}
    pass: ${ADMIN_FIRST_PASSWORD}
  second:
    user: ${ADMIN_SECOND_USER}
    login: ${ADMIN_SECOND_LOGIN}
    pass: ${ADMIN_SECOND_PASSWORD}
  third:
    user: ${ADMIN_THIRD_USER}
    login: ${ADMIN_THIRD_LOGIN}
    pass: ${ADMIN_THIRD_PASSWORD}

