spring:
  application:
    name: linkedin-bot
  liquibase:
    change-log: 'classpath:db-migrations/changelog.xml'
    user: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:6361}
  datasource:
    url: "jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:postgres}?currentSchema=${DATABASE_SCHEMA:public}"
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:6361}
    platform: POSTGRESQL
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
      show_sql: true
    properties.hibernate.temp.use_jdbc_metadata_defaults: false

vaadin:
  launch-browser: false

logging:
  level:
    org.atmosphere: warn
server:
  port: 8080

telegram:
  bot:
    name: cv_helper_bot
    token: 5115367582:AAEIQ4sDhCzKv7nNel18fUQf5sI2h43M4Xo
    admin: kezikoff