spring:
  application:
    name: linkedin-bot
  liquibase:
    change-log: 'classpath:db-migrations/changelog.xml'
    user: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:6361}
  datasource:
    url: "jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:postgres}?currentSchema=${DATABASE_SCHEMA:public}"
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:6361}
    platform: POSTGRESQL
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
      show_sql: true
    properties.hibernate.temp.use_jdbc_metadata_defaults: false

vaadin:
  launch-browser: false

logging:
  level:
    org.atmosphere: warn
server:
  port: 8080

telegram:
  bot:
    name: cvtest_bot
    token: 5277446388:AAFvoT_kUSviZyVnb48nYhv9Qwo3OPfj_UQ
    admin: kezikoff

admin:
  first:
    user: ${ADMIN_FIRST_USER:123}
    login: ${ADMIN_FIRST_LOGIN:123}
    pass: ${ADMIN_FIRST_PASSWORD:123}
  second:
    user: ${ADMIN_SECOND_USER:1234}
    login: ${ADMIN_SECOND_LOGIN:1234}
    pass: ${ADMIN_SECOND_PASSWORD:1234}
  third:
    user: ${ADMIN_THIRD_USER:12}
    login: ${ADMIN_THIRD_LOGIN:12}
    pass: ${ADMIN_THIRD_PASSWORD:12}